// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943

// components/TopActionBar.templ

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TopActionBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"h-14 border-b border-gray-700 bg-gray-800 flex items-center justify-between px-4\"><div class=\"flex items-center space-x-2\"><h1 class=\"text-lg font-semibold\">HexTest</h1><span class=\"text-sm text-gray-400\">v0.1-templ</span></div><div class=\"flex items-center space-x-2\"><!-- NEW: open confirm modal --><button type=\"button\" class=\"px-3 py-1.5 text-sm bg-gray-700 rounded-md hover:bg-gray-600 flex items-center\" hx-get=\"/json/new/confirm\" hx-target=\"#modal-root\" hx-swap=\"innerHTML\">New</button><!-- IMPORT: open import modal (with warning) --><button type=\"button\" class=\"px-3 py-1.5 text-sm bg-gray-700 rounded-md hover:bg-gray-600 flex items-center\" hx-get=\"/json/import\" hx-target=\"#modal-root\" hx-swap=\"innerHTML\">Import</button><!-- EXPORT: normal GET → browser download --><a href=\"/json/export\" class=\"px-3 py-1.5 text-sm bg-gray-700 rounded-md hover:bg-gray-600 flex items-center\">Export</a> <button class=\"px-3 py-1.5 text-sm bg-green-600 hover:bg-green-700 text-white rounded-md flex items-center\">Run</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
